sudo: required
language: node_js
node_js:
 - "6.11.2"
services:
  - docker
before_script:
 - bash docker-start.sh &
script: "npm run-script test-travis"
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - bash docker-stop.sh
